### ISSUE TITLE
Running in 2018

### ISSUE THREAD

**Issue by kewp** [gheja/untitled13#16]
Any idea how to run this now ?

I replaced the `socket.io.js` reference in `index.html` to a CDN copy of 0.9.16 (the version defined in package.json)

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js"></script>
```

Then did an `npm install` in **src** and ran `node server.js` (note: didn't work on windows, got a ton of visual studio errors. running on Debian VM).

Seems to start up fine... browsed to **localhost:8080** but all I get is `Initialising...`

**Comment by kewp** [comment]
Hmmm OK I see you need to change where the server is defined.

I changed `13312.js` line 2839 (function `B.init`) to this:

```
A.server_url = 'http://localhost:8080'
```

Not sure if that is how this is suppose to work ? But it starts. GIves me a game URL. But then when I try open someone else (open the game in two tabs) it crashes....

```
[1535368214742] [zsbcz5FB1SRRrW5wCjjc] sending: welcome zsbcz5FB1SRRrW5wCjjc,1
   debug - websocket writing 5:::{"name":"welcome","args":[["zsbcz5FB1SRRrW5wCjjc",1]]}
[1535368214827] [zsbcz5FB1SRRrW5wCjjc] sending: game_disconnected undefined
   debug - websocket writing 5:::{"name":"game_disconnected","args":[null]}
```

Is there any way to easily run the graphics / animations without the server ? I want to understand how you built up your drawing procedures (based on the post mortem you wrote).

**Comment by kewp** [comment]
OK, it's working - I tried to open 2 new tabs, but didn't realise the first one re-loaded with the start game dialogue. (So just open one new tab with the url, select ready, and go back to the first and do the same).

Works great. Nice game :)

**Comment by gheja** [comment]
Thanks for playing the game and for the kind words :)
